{
 "title": "System",
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device=\"sda\", instance=\"localhost:9100\"}[10m])",
     "legendFormat": "Количество записей ввода-вывода"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"localhost:9100\"}/1024/1024",
     "legendFormat": "Доступная оперативная память"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100-(avg by (instance)(irate(node_cpu_seconds_total{instance=\"localhost:9100\", mode=\"idle\"}[5m])))*100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"localhost:9100\", mountpoint=\"/\"}/1024/1024",
     "legendFormat": "Доступная память"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"localhost:9100\", mountpoint=\"/\"}/1024/1024 - node_filesystem_avail_bytes{instance=\"localhost:9100\", mountpoint=\"/\"}/1024/1024",
     "legendFormat": "Занятая память"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"localhost:9100\", mountpoint=\"/\"}/1024/1024",
     "legendFormat": "Вся память"
    }
   ]
  }
 ]
}